contact_links:
  - name: Are you looking for documentation on counting-to-90?
    url: https://mtwente.github.io/counting-to-90
    about: Please see the documentation for counting-to-90 on its GitHub Pages page.
  - name: Do you want to discuss counting-to-90 with the community?
    url: https://github.com/mtwente/counting-to-90/discussions
    about: Please see the discussions page for counting-to-90.
blank_issues_enabled: true
